apiVersion: v1
kind: Service
metadata:
  name: @@@NODEPORT_NAME@@@
  namespace: @@@NAMESPACE_NAME@@@
spec:
  selector:
    app: vcluster
    release: @@@VCLUSTER_NAME@@@
  ports:
    - name: https
      port: 443
      targetPort: 8443
      protocol: TCP
  type: NodePort
